site_name: spaceprime
site_description: A python package to facilitate spatially explicit coalescent modeling in msprime
site_author: connor-french
site_url: https://connor-french.github.io/spaceprime
repo_url: https://github.com/connor-french/spaceprime

copyright: "Copyright &copy; 2024 - 2024 Connor French"

theme:
    palette:
        - scheme: default
          #   primary: blue
          #   accent: indigo
          toggle:
              icon: material/toggle-switch-off-outline
              name: Switch to dark mode
        - scheme: slate
          primary: indigo
          accent: indigo
          toggle:
              icon: material/toggle-switch
              name: Switch to light mode
    name: material
    icon:
        repo: fontawesome/brands/github
    # logo: assets/logo.png
    # favicon: assets/favicon.png
    features:
        - navigation.instant
        - navigation.tracking
        - navigation.top
        - search.highlight
        - search.share
    custom_dir: "docs/overrides"
    font:
        text: Google Sans
        code: Regular

plugins:
    - search
    - mkdocstrings:
        handlers:
            python:
                options:
                    paths: [spaceprime]
                    docstring_style: google
                    docstring_section_style: table

    - git-revision-date
    - git-revision-date-localized:
          enable_creation_date: true
          type: timeago
    # - pdf-export
    - mkdocs-jupyter:
          include_source: True
          ignore_h1_titles: True
          execute: True
          allow_errors: false
          ignore: ["conf.py"]
          execute_ignore: ["*ignore.ipynb"]
    - callouts
          
markdown_extensions:
    - admonition
    - abbr
    - attr_list
    - def_list
    - footnotes
    - meta
    - md_in_html
    - nl2br
    - admonition
    - pymdownx.superfences
    - pymdownx.details
    - pymdownx.highlight:
          linenums: true
    - toc:
          permalink: true

# extra:
#     analytics:
#         provider: google
#         property: UA-XXXXXXXXX-X

nav:
    - Home: index.md
    - Vignettes:
        - examples/intro.ipynb
        - Suitability to deme size transformation functions: trans-fns.md    
    - Reference:
        - utilities module: utilities.md
        - demography module: demography.md
        - analysis module: analysis.md
    - Contributing: contributing.md
    - Changelog: changelog.md
    
    #- Installation: installation.md
    #- Usage: usage.md
    #- FAQ: faq.md
    #- Report Issues: https://github.com/connor-french/spaceprime/issues