[project]
name = "spaceprime"
version = "0.0.3"
dynamic = [
    "dependencies",
]
description = "A python package to facilitate spatially explicit coalescent modeling in msprime"
readme = "README.md"
requires-python = ">=3.8"
keywords = [
    "spaceprime",
]
license = {text = "MIT License"}
authors = [
  {name = "Connor French", email = "french.connor.m@gmail.com"},
]
classifiers = [
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Natural Language :: English",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
]

[project.entry-points."console_scripts"]
spaceprime = "spaceprime.cli:main"

[project.optional-dependencies]
all = [
    "spaceprime[extra]",
]

extra = [
    "esda >= 2.5.1",
    "libpysal >= 4.10",
    "sklearn",
    "itertools",
    "scipy",
]


[tool]
[tool.setuptools.packages.find]
include = ["spaceprime*"]
exclude = ["docs*"]

[tool.setuptools.dynamic]
dependencies = {file = ["requirements.txt"]}


[tool.distutils.bdist_wheel]
universal = true


[tool.bumpversion]
current_version = "0.0.3"
commit = true
tag = true

[[tool.bumpversion.files]]
filename = "pyproject.toml"
search = 'version = "{current_version}"'
replace = 'version = "{new_version}"'

[[tool.bumpversion.files]]
filename = "spaceprime/__init__.py"
search = '__version__ = "{current_version}"'
replace = '__version__ = "{new_version}"'


[tool.flake8]
exclude = [
    "docs",
]
max-line-length = 88


[project.urls]
Homepage = "https://github.com/connor-french/spaceprime"

[build-system]
requires = ["setuptools>=64", "setuptools_scm>=8"]
build-backend = "setuptools.build_meta"