on:
  push:
    branches:
      - main

jobs:
  tests:
    name: "deploy-docs"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Pixi
        run: |
            curl -fsSL https://pixi.sh/install.sh | bash
            echo "$HOME/.pixi/bin" >> $GITHUB_PATH

      - name: Setup Pixi environment
        run: pixi install -e dev

      - name: Test GDAL installation
        run: |
          pixi run python -c "from osgeo import gdal"
          pixi run gdalinfo --version

      - name: Install package
        run: |
          pixi run pip install .

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Build docs
        run: |
          pixi run quarto render docs/

      - name: Save docs
        uses: actions/upload-artifact@v4
        with:
          name: docs-html
          path: docs/_site

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/_site
          publish_branch: gh-pages