on:
    push:
        branches:
            - main
            - master
    pull_request:
        branches:
            - main
            - master

name: macOS build
jobs:
    py-check:
        runs-on: ${{ matrix.config.os }}
        name: ${{ matrix.config.os }} (${{ matrix.config.py }})
        strategy:
            fail-fast: false
            matrix:
                config:
                    - { os: macos-latest, py: "3.10" }
                    - { os: macos-latest, py: "3.11" }
                    - { os: macos-latest, py: "3.12" }
                    - { os: macos-latest, py: "3.13" }
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4
            - name: Setup Python
              uses: actions/setup-python@v5
              with:
                  python-version: ${{ matrix.config.py }}
            - name: Install GSL
              run: brew install gsl
            - name: Install Pixi
              uses: prefix-dev/setup-pixi@v0.8.3
              
            - name: Install dependencies and test
              run: |
                  pixi install --all
                  pixi run python -c "from osgeo import gdal; print(f\"GDAL version: {gdal.VersionInfo()}\")"
                  pixi run -e all test
            - name: Upload coverage reports to Codecov
              uses: codecov/codecov-action@v4.0.1
              with:
                  token: ${{ secrets.CODECOV_TOKEN }}
