on:
    push:
        branches:
            - main
            - master
    pull_request:
        branches:
            - main
            - master

name: Linux build
jobs:
    py-check:
        runs-on: ${{ matrix.config.os }}
        name: ${{ matrix.config.os }} (${{ matrix.config.py }})
        strategy:
            fail-fast: false
            matrix:
                config:
                    - { os: ubuntu-latest, py: "3.10" }
                    - { os: ubuntu-latest, py: "3.11" }
                    - { os: ubuntu-latest, py: "3.12" }
                    - { os: ubuntu-latest, py: "3.13" }
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4
            - name: Setup Python
              uses: actions/setup-python@v5
              with:
                  python-version: ${{ matrix.config.py }}
            - name: Install Pixi
              run: |
                  curl -fsSL https://pixi.sh/install.sh | bash
                  echo "$HOME/.pixi/bin" >> $GITHUB_PATH
            - name: Install dependencies and test
              run: |
                  pixi install
                  pixi run python -c "from osgeo import gdal; print(f\"GDAL version: {gdal.VersionInfo()}\")"
                  pixi run test
            - name: Upload coverage reports to Codecov
              uses: codecov/codecov-action@v4.0.1
              with:
                  token: ${{ secrets.CODECOV_TOKEN }}

